### ISSUE TITLE
일정 알림봇

### ISSUE THREAD

**Issue by thephunkmonk** [pladata-encore/DE32-2rd_team6#10]
- [x] 우리 팀의 칸반회의 시간 알림 (9:15)  설정
- [ ] 점심 시간 알림 설정
- [ ] 여유가 된다면 휴게시간 5분전 알림

**Comment by lsiwh37249** [comment]
일정 알림봇 실습 내용
(https://github.com/pladata-encore/DE32_101/issues/70)
